apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
spec:
  name: immich
  owner: immich_app
  cluster:
    name: cloudnative-pg-cluster
  extensions:
    - name: vector
    - name: cube
    - name: earthdistance
    - name: vchord
      version: "0.4.3"
