apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mixin-generated

patches:
  - target:
      kind: PrometheusRule
      name: kafka-rules
    path: kafka-rules-patch.yaml
  - target:
      kind: PrometheusRule
      name: kafka-exporter-topic
    path: kafka-exporter-topic-patch.yaml
