apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: strimzi
    role: alert-rules
  name: kafka-connect
spec:
  groups:
    - name: kafka-connect
      rules:
        - alert: ConnectContainersDown
          annotations:
            description: All Kafka Connect containers have been down or in CrashLookBackOff status for 3 minutes
            summary: All Kafka Connect containers down or in CrashLookBackOff status
          expr: absent(container_last_seen{container=~".+-connect",pod=~".+-connect-.+"})
          for: 3m
          labels:
            severity: major
        - alert: ConnectFailedConnector
          annotations:
            description: Kafka instance on pod {{ $labels.namespace }}/{{ $labels.pod }} has {{ $value }} connector(s) in failed state during last 5 minutes
            summary: Kafka Connect Connector Failure
          expr: sum(kafka_connect_connector_status{status="failed"}) by (namespace, pod) > 0
          for: 5m
          labels:
            severity: major
        - alert: ConnectFailedTask
          annotations:
            description: Kafka instance on pod {{ $labels.namespace }}/{{ $labels.pod }} has {{ $value }} task(s) in failed state during last 5 minutes
            summary: Kafka Connect Task Failure
          expr: sum(kafka_connect_worker_connector_failed_task_count) by (namespace, pod) > 0
          for: 5m
          labels:
            severity: major
