apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: strimzi
    role: alert-rules
  name: kafka-certificates
spec:
  groups:
    - interval: 1m0s
      name: kafka-certificates
      rules:
        - alert: CertificateExpiration
          annotations:
            description: Certificate of type {{ $labels.type }} in cluster {{ $labels.cluster }} in namespace {{ $labels.resource_namespace }} will expire in less than 30 days
            summary: Certificate will expire in less than 30 days
          expr: |
            strimzi_certificate_expiration_timestamp_ms/1000 - time() < 30 * 24 * 60 * 60
          for: 5m
          labels:
            severity: warning
