apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-2-replica
provisioner: io.openebs.csi-mayastor
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  protocol: nvmf
  repl: "2"
