apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-config
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  data:
    - secretKey: github_app_id
      remoteRef:
        key: "GitHub App Information (Self-Hosted Runners)"
        property: appId
    - secretKey: github_app_installation_id
      remoteRef:
        key: "GitHub App Information (Self-Hosted Runners)"
        property: installationId
    - secretKey: github_app_private_key
      remoteRef:
        key: "GitHub App Credentials (Self-Hosted Runners)"
        property: private-key.pem
