apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-admin
spec:
  bucketName: loki-admin
  storageClassName: ceph-bucket
  additionalConfig:
    maxSize: 10Gi
    bucketOwner: loki-user
