apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-ruler
spec:
  bucketName: loki-ruler
  storageClassName: ceph-bucket
  additionalConfig:
    maxSize: 20Gi
    bucketOwner: loki-user
