apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudnative-pg-cluster-metrics
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: cloudnative-pg-cluster
  podMetricsEndpoints:
    - port: metrics
