apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-csi-rbd-provisioner
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/rook
  data:
    - secretKey: userID
      remoteRef:
        key: "rook-csi-rbd-provisioner"
        property: userID
    - secretKey: userKey
      remoteRef:
        key: "rook-csi-rbd-provisioner"
        property: userKey
