apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./csi-rbd-node-secret.yaml
  - ./csi-rbd-provisioner-secret.yaml
  - ./external-cluster-user-command-configmap.yaml
  - ./mon-endpoints-configmap.yaml
  - ./mon-secret.yaml
  - ./rgw-admin-ops-user-secret.yaml
  - ./storageclass-rbd.yaml
