apiVersion: v1
data:
  data: "host01=192.168.0.150:6789,host02=192.168.0.151:6789,host03=192.168.0.152:6789,host04=192.168.0.153:6789"
  mapping: '{}'
  maxMonId: "3"
kind: ConfigMap
metadata:
  name: rook-ceph-mon-endpoints
  namespace: rook-ceph
