apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-mon
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/rook
  data:
    - secretKey: admin-secret
      remoteRef:
        key: "rook-ceph-mon"
        property: admin-secret
    - secretKey: ceph-secret
      remoteRef:
        key: "rook-ceph-mon"
        property: ceph-secret
    - secretKey: ceph-username
      remoteRef:  
        key: "rook-ceph-mon"
        property: ceph-username
    - secretKey: cluster-name
      remoteRef:
        key: "rook-ceph-mon"
        property: cluster-name
    - secretKey: fsid
      remoteRef:
        key: "rook-ceph-mon"
        property: fsid
    - secretKey: mon-secret
      remoteRef:
        key: "rook-ceph-mon"
        property: mon-secret
