apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rgw-admin-ops-user
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/rook
  data:
    - secretKey: accessKey
      remoteRef:
        key: "rgw-admin-ops-user"
        property: accessKey
    - secretKey: secretKey
      remoteRef:
        key: "rgw-admin-ops-user"
        property: secretKey
