apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://strimzi.io/charts
    chart: strimzi-kafka-operator
    targetRevision: 0.50.0
    helm:
      valuesObject:
        replicas: 3
        podDisruptionBudget:
          enabled: true
        watchAnyNamespace: true
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: strimzi-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
