apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-alertmanager-global-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    name: mimir-alertmanager-global-config
    template:
      engineVersion: v2
      data:
        alertmanager.yaml: |
          route:
            receiver: discord
          receivers:
            - name: discord
              discord_configs:
                - webhook_url: "{{ .DISCORD_WEBHOOK_URL }}"
  data:
    - secretKey: DISCORD_WEBHOOK_URL
      remoteRef:
        key: "Mimir Alertmanager Discord Webhook"
        property: URL
