apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-alertmanager-global-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    name: mimir-alertmanager-global-config
    template:
      engineVersion: v2
      data:
        alertmanager.yaml: |
          route:
            receiver: discord
          receivers:
            - name: discord
              discord_configs:
                - webhook_url: "{{ .DISCORD_WEBHOOK_URL }}"
                  title: "[{{ "{{" }} .Status | toUpper {{ "}}" }}{{ "{{" }} if eq .Status \"firing\" {{ "}}" }}:{{ "{{" }} .Alerts.Firing | len {{ "}}" }}{{ "{{" }} if gt (.Alerts.Resolved | len) 0 {{ "}}" }}, RESOLVED:{{ "{{" }} .Alerts.Resolved | len {{ "}}" }}{{ "{{" }} end {{ "}}" }}{{ "{{" }} end {{ "}}" }}] {{ "{{" }} .GroupLabels.SortedPairs.Values | join \" \" {{ "}}" }} {{ "{{" }} if gt (len .CommonLabels) (len .GroupLabels) {{ "}}" }}({{ "{{" }} with .CommonLabels.Remove .GroupLabels.Names {{ "}}" }}{{ "{{" }} .Values | join \" \" {{ "}}" }}{{ "{{" }} end {{ "}}" }}){{ "{{" }} end {{ "}}" }}"
                  message: |
                    {{ "{{" }} if gt (len .Alerts.Firing) 0 {{ "}}" }}
                    ## Firing
                    {{ "{{" }} range .Alerts.Firing {{ "}}" }}
                    ### Labels
                    {{ "{{" }} range .Labels.SortedPairs {{ "}}" }}
                    - {{ "{{" }} .Name {{ "}}" }} = {{ "{{" }} .Value {{ "}}" }}
                    {{ "{{" }} end {{ "}}" }}
                    {{ "{{" }} if len .Annotations {{ "}}" }}
                    ### Annotations
                    {{ "{{" }} range .Annotations.SortedPairs {{ "}}" }}
                    - {{ "{{" }} .Name {{ "}}" }} = {{ "{{" }} .Value {{ "}}" }}
                    {{ "{{" }} end {{ "}}" }}
                    {{ "{{" }} end {{ "}}" }}
                    {{ "{{" }} $expr := queryFromGeneratorURL .GeneratorURL {{ "}}" }}
                    {{ "{{" }} $hasExpr := ne $expr "" {{ "}}" }}
                    ### Links
                    {{ "{{" }} if $hasExpr {{ "}}" }}
                    - [Explore](<{{ "{{" }} grafanaExploreURL "https://grafana.chik4ge.me" "Mimir" "now-1h" "now" $expr {{ "}}" }}>)
                    {{ "{{" }} else {{ "}}" }}
                    - [Source](<https://mimir.chik4ge.me{{ "{{" }} .GeneratorURL {{ "}}" }}>)
                    {{ "{{" }} end {{ "}}" }}
                    {{ "{{" }} end {{ "}}" }}
                    {{ "{{" }} end {{ "}}" }}
                    {{ "{{" }} if gt (len .Alerts.Resolved) 0 {{ "}}" }}
                    ## Resolved
                    {{ "{{" }} range .Alerts.Resolved {{ "}}" }}
                    ### Labels
                    {{ "{{" }} range .Labels.SortedPairs {{ "}}" }}
                    - {{ "{{" }} .Name {{ "}}" }} = {{ "{{" }} .Value {{ "}}" }}
                    {{ "{{" }} end {{ "}}" }}
                    {{ "{{" }} if len .Annotations {{ "}}" }}
                    ### Annotations
                    {{ "{{" }} range .Annotations.SortedPairs {{ "}}" }}
                    - {{ "{{" }} .Name {{ "}}" }} = {{ "{{" }} .Value {{ "}}" }}
                    {{ "{{" }} end {{ "}}" }}
                    {{ "{{" }} end {{ "}}" }}
                    {{ "{{" }} $expr := queryFromGeneratorURL .GeneratorURL {{ "}}" }}
                    {{ "{{" }} $hasExpr := ne $expr "" {{ "}}" }}
                    ### Links
                    {{ "{{" }} if $hasExpr {{ "}}" }}
                    - [Explore](<{{ "{{" }} grafanaExploreURL "https://grafana.chik4ge.me" "Mimir" "now-1h" "now" $expr {{ "}}" }}>)
                    {{ "{{" }} else {{ "}}" }}
                    - [Source](<https://mimir.chik4ge.me{{ "{{" }} .GeneratorURL {{ "}}" }}>)
                    {{ "{{" }} end {{ "}}" }}
                    {{ "{{" }} end {{ "}}" }}
                    {{ "{{" }} end {{ "}}" }}
  data:
    - secretKey: DISCORD_WEBHOOK_URL
      remoteRef:
        key: "Mimir Alertmanager Discord Webhook"
        property: URL
