apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    path: manifests/networking/cloudflared
    repoURL: https://github.com/chik4ge-homelab/homelab-applications
    targetRevision: main
  destination:
    namespace: cloudflared
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
