apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel-ingress-controller
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: manifests/platform/base/networking/cloudflare-tunnel-ingress-controller
    - repoURL: https://helm.strrl.dev
      chart: cloudflare-tunnel-ingress-controller
      targetRevision: 0.0.22
      helm:
        valuesObject:
          cloudflare:
            secretRef:
              name: cloudflare-tunnel-api-token-secret
              accountIDKey: account_id
              tunnelNameKey: tunnel_name
              apiTokenKey: api_token
  destination:
    namespace: cloudflare-tunnel-ingress-controller
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
