apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proxmox-exporter

resources:
  - secrets/proxmox-secret.yaml
  - secrets/prometheus-pve-exporter-secret.yaml
  - scrapeconfig/proxmox-exporter.yaml
