apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cloudnative-pg-cluster
spec:
  instances: 3
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5-0.4.3
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  bootstrap:
    initdb:
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
  managed:
    roles:
      - name: immich_app
        login: true
        passwordSecret:
          name: immich-db-credentials
  storage:
    storageClass: ceph-rbd
    size: 20Gi
