apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alloy

resources:
  - rules/mixin-generated
  - secrets/alertmanager-discord-webhook.yaml
  - gateway/httproute.yaml

configMapGenerator:
  - name: alloy-config
    files:
      - config.alloy=config/alloy-config.alloy

generatorOptions:
  disableNameSuffixHash: true
