apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tradukisto
  namespace: tradukisto
  labels:
    app.kubernetes.io/name: tradukisto
spec:
  parentRefs:
    - name: envoy-gateway-internal
      namespace: envoy-gateway
      sectionName: https
  hostnames:
    - trad.chik4ge.me
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/
      backendRefs:
        - name: tradukisto-server
          port: 8081
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: tradukisto-client
          port: 80
