apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: mimir-blocks
spec:
  bucketName: mimir-blocks
  storageClassName: ceph-bucket
  additionalConfig:
    maxSize: 120Gi
    bucketOwner: mimir-user
