apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: mimir-ruler
spec:
  bucketName: mimir-ruler
  storageClassName: ceph-bucket
  additionalConfig:
    maxSize: 10Gi
    bucketOwner: mimir-user
