apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: http://pajikos.github.io/home-assistant-helm-chart/
      chart: home-assistant
      targetRevision: 0.3.41
      helm:
        valuesObject:
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi
          podAnnotations:
            descheduler.alpha.kubernetes.io/prefer-no-eviction: "true"
          ingress:
            enabled: false
          persistence:
            enabled: true
            storageClass: ceph-rbd
            size: 20Gi
          configuration:
            enabled: true
            forceInit: true
            templateConfig: |-
              # Loads default set of integrations. Do not remove.
              default_config:

              http:
                use_x_forwarded_for: true
                trusted_proxies:
                  - 127.0.0.1
                  - 10.244.0.0/16
              
              prometheus:
                requires_auth: false

              # Load frontend themes from the themes folder
              frontend:
                themes: !include_dir_merge_named themes

              automation: !include automations.yaml
              script: !include scripts.yaml
              scene: !include scenes.yaml
          serviceMonitor:
            enabled: true
            scrapeInterval: 5m

    - repoURL: https://charts.derwitt.dev
      chart: home-assistant-matter-server 
      targetRevision: 3.1.3
      helm:
        valuesObject:
          networkInterface: net0
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
          podAnnotations:
            descheduler.alpha.kubernetes.io/prefer-no-eviction: "true"
          persistence:
            storageClassName: ceph-rbd
            size: 2Gi

    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: manifests/workloads/home-assistant
  destination:
    namespace: home-assistant
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: "privileged"
