apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tradukisto
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chik4ge-homelab/homelab-applications
    targetRevision: main
    path: manifests/workloads/tradukisto
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: tradukisto
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
