apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/mkilchhofer/unifi-chart/unifi
      chart: unifi
      targetRevision: 1.14.1
      helm:
        valuesObject:
          persistence:
            enabled: true
            size: 10Gi
            storageClass: ceph-rbd
            skipuninstall: true
          timezone: Asia/Tokyo

          ingress:
            enabled: false

          resources:
            requests:
             cpu: 100m
             memory: 768Mi
            limits:
             memory: 1536Mi
          jvmMaxHeapSize: 1024M
          podAnnotations:
            descheduler.alpha.kubernetes.io/prefer-no-eviction: "true"

          controllerService:
            type: LoadBalancer
            loadBalancerIP: 192.168.1.99
            annotations:
              lbipam.cilium.io/sharing-key: "unifi-shared"
          stunService:
            type: LoadBalancer
            loadBalancerIP: 192.168.1.99
            annotations:
              lbipam.cilium.io/sharing-key: "unifi-shared"
          discoveryService:
            type: LoadBalancer
            loadBalancerIP: 192.168.1.99
            annotations:
              lbipam.cilium.io/sharing-key: "unifi-shared"

    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: manifests/workloads/unifi

  destination:
    namespace: unifi
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: "privileged"
