apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/mkilchhofer/unifi-chart/unifi
      chart: unifi
      targetRevision: 1.14.1
      helm:
        valuesObject:
          persistence:
            enabled: true
            size: 10Gi
            storageClass: mayastor-3-replica
            skipuninstall: true
          timezone: Asia/Tokyo

          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            hosts:
              - unifi.chik4ge.me
            tls:
              - hosts:
                  - unifi.chik4ge.me

          resources:
            requests:
             cpu: 100m
             memory: 768Mi
            limits:
             memory: 1536Mi
          jvmMaxHeapSize: 1024M

          controllerService:
            type: LoadBalancer
            loadBalancerIP: 192.168.1.99
            annotations:
              lbipam.cilium.io/sharing-key: "unifi-shared"
          stunService:
            type: LoadBalancer
            loadBalancerIP: 192.168.1.99
            annotations:
              lbipam.cilium.io/sharing-key: "unifi-shared"
          discoveryService:
            type: LoadBalancer
            loadBalancerIP: 192.168.1.99
            annotations:
              lbipam.cilium.io/sharing-key: "unifi-shared"

  destination:
    namespace: unifi
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: "privileged"
