apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ip-pool"
spec:
  blocks:
    - start: "192.168.2.1"
      stop: "192.168.2.254"
    - start: "192.168.1.4"
      stop: "192.168.1.99"
