apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
        # mimirがSASL/PLAINでのみ接続可能なため、対応までコメントアウト
        # authentication:
        #   type: scram-sha-512
    # authorization:
    #   type: simple
    version: 4.1.1
    metadataVersion: "4.1"
    config:
      auto.create.topics.enable: "false"

      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2

      log.retention.hours: 2
      log.segment.bytes: 1073741824
      log.cleanup.policy: delete

      message.max.bytes: 10485760
      replica.fetch.max.bytes: 10485760
      max.request.size: 10485760
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yaml
  entityOperator:
    topicOperator:
      watchedNamespace: strimzi-kafka
      reconciliationIntervalMs: 60000
      # Resources requests and limits (recommended)
      # resources:
      #   requests:
      #     memory: 512Mi
      #     cpu: "1"
      #   limits:
      #     memory: 512Mi
      #     cpu: "1"
    userOperator:
      watchedNamespace: strimzi-kafka
      reconciliationIntervalMs: 60000
      # Resources requests and limits (recommended)
      # resources:
      #   requests:
      #     memory: 512Mi
      #     cpu: "1"
      #   limits:
      #     memory: 512Mi
      #     cpu: "1"
  kafkaExporter:
    groupRegex: ".*"
    topicRegex: ".*"
    groupExcludeRegex: "^excluded-.*"
    topicExcludeRegex: "^excluded-.*"
    # resources:
    #   requests:
    #     cpu: 200m
    #     memory: 64Mi
    #   limits:
    #     cpu: 500m
    #     memory: 128Mi
