apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/descheduler/
      targetRevision: 0.34.0
      chart: descheduler
      helm:
        valuesObject:
          deschedulerPolicy:
            metricsProviders:
              - source: Prometheus
                prometheus:
                  url: http://mimir-gateway.mimir.svc.cluster.local/prometheus
            profiles:
              - name: homelab-policy
                pluginConfig:
                  - name: DefaultEvictor
                    args:
                      nodeFit: true
                      ignorePvcPods: false
                  - name: RemovePodsViolatingNodeTaints
                  # TODO: 必要なpodに対し、descheduler.alpha.kubernetes.io/prefer-no-eviction アノテーションを付与したあとに有効化する
                  # - name: RemovePodsViolatingNodeAffinity
                  #   args:
                  #     nodeAffinityType: preferredDuringSchedulingIgnoredDuringExecution
                  - name: RemovePodsViolatingInterPodAntiAffinity
                  - name: RemovePodsViolatingTopologySpreadConstraint
                    args:
                      constraints:
                        - DoNotSchedule
                        - ScheduleAnyway
                  - name: RemoveDuplicates
                    args:
                      excludeOwnerKinds:
                        - ReplicaSet
                  - name: LowNodeUtilization
                    args:
                      useDeviationThresholds: true
                      thresholds:
                        MetricResource: 10
                      targetThresholds:
                        MetricResource: 10
                      metricsUtilization:
                        source: Prometheus
                        prometheus:
                          query: |
                            label_replace(
                              (
                                1 - (
                                  node_memory_MemAvailable_bytes{job="node-exporter"}
                                  /
                                  node_memory_MemTotal_bytes{job="node-exporter"}
                                )
                              )
                              * on(instance, job) group_left(nodename)
                                node_uname_info{job="node-exporter", nodename=~"k8s-.*"},
                              "instance", "$1", "nodename", "(.+)"
                            )
                plugins:
                  deschedule:
                    enabled:
                      - RemovePodsViolatingNodeTaints
                      # - RemovePodsViolatingNodeAffinity
                      - RemovePodsViolatingInterPodAntiAffinity
                  balance:
                    enabled:
                      - RemovePodsViolatingTopologySpreadConstraint
                      - RemoveDuplicates
                      - LowNodeUtilization

  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
