apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.5.1
      helm:
        valuesObject:
          controller:
            type: statefulset
            replicas: 3
          alloy:
            clustering:
              enabled: true
            stabilityLevel: "experimental" # to use scrapeconfigs
            configMap:
              create: false
              name: "alloy-config"
              key: "config.alloy"
            resources:
              requests:
                cpu: "50m"
                memory: "1.5Gi"
              limits:
                memory: "4Gi"
          ingress:
            enabled: false
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: manifests/platform/services/observability/alloy
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: alloy
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
