apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: manifests/platform/services/observability/mimir
    - repoURL: https://grafana.github.io/helm-charts
      chart: mimir-distributed
      targetRevision: 6.0.5
      helm:
        valuesObject:
          compactor:
            persistentVolume:
              size: 20Gi
              storageClass: ceph-rbd
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 1Gi
            podAnnotations:
              descheduler.alpha.kubernetes.io/prefer-no-eviction: "true"

          distributor:
            replicas: 2
            resources:
              limits:
                memory: 6Gi
              requests:
                cpu: 100m
                memory: 192Mi

          kafka:
            enabled: false
          nginx:
            enabled: false

          gateway:
            enabledNonEnterprise: true
            replicas: 2
            ingress:
              enabled: true
              ingressClassName: nginx
              hosts:
                - host: mimir.chik4ge.me
                  paths:
                    - path: /
                      pathType: Prefix
              tls:
                - hosts:
                    - mimir.chik4ge.me

          ingester:
            zoneAwareReplication:
              enabled: false
            replicas: 3
            persistentVolume:
              size: 25Gi
              storageClass: ceph-rbd
            resources:
              requests:
                cpu: 150m
                memory: 1920Mi
              limits:
                memory: 5Gi
                    
          store_gateway:
            zoneAwareReplication:
              enabled: false
            replicas: 3
            persistentVolume:
              storageClass: ceph-rbd
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi

          chunks-cache:
            enabled: true
            replicas: 1
            allocatedMemory: 4096
            resources:
              requests:
                cpu: 10m
                memory: 320Mi
              limits:
                memory: 4Gi

          alertmanager:
            replicas: 2
            persistentVolume:
              storageClass: ceph-rbd
            resources:
              requests:
                memory: 64Mi
            podAnnotations:
              descheduler.alpha.kubernetes.io/prefer-no-eviction: "true"
            extraEnvFrom:
              - secretRef:
                  name: mimir-alertmanager-discord-webhook
            fallbackConfig: |
              route:
                receiver: discord
              receivers:
                - name: discord
                  discord_configs:
                    - webhook_url: "${DISCORD_WEBHOOK_URL}"

          metaMonitoring:
            serviceMonitor:
              enabled: true

          index-cache:
            enabled: true
            replicas: 3
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi

          metadata-cache:
            enabled: true
            replicas: 3
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi

          results-cache:
            enabled: true
            replicas: 3
            resources:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                memory: 256Mi
          
          ruler:
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 512Mi

          minio:
            enabled: false

          global:
            extraEnvFrom:
              - secretRef:
                  name: mimir-blocks
              - configMapRef:
                  name: mimir-blocks
              - secretRef:
                  name: kafka-password

          runtimeConfig:
            ingester_limits:
              max_ingestion_rate: 999999999
            distributor_limits:
              max_ingestion_rate: 999999999

          mimir:
            structuredConfig:
              common:
                storage:
                  backend: s3
                  s3:
                    endpoint: "${BUCKET_HOST}:${BUCKET_PORT}"
                    access_key_id: "${AWS_ACCESS_KEY_ID}"
                    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
                    insecure: true
              limits:
                ingestion_rate: 999999999
                out_of_order_time_window: 24h
                compactor_blocks_retention_period: 30d
                max_global_series_per_user: 0
              distributor:
                remote_timeout: 30m
              server:
                http_server_read_timeout: 30m
                http_server_write_timeout: 30m
              blocks_storage:
                s3:
                  bucket_name: mimir-blocks
                bucket_store:
                  chunks_cache:
                    memcached:
                      timeout: 15s
              ingest_storage:
                kafka:
                  address: kafka-cluster-kafka-bootstrap.strimzi-kafka.svc.cluster.local:9092
                  topic: mimir-ingest
                  auto_create_topic_enabled: false
                  # strimzi-kafkaがSASL/PLAINに対応していないため、mimir側でSASL/SCRAMを指定できるようになるまでコメントアウト
                  # sasl_username: mimir
                  # sasl_password: "${KAFKA_PASSWORD}"
              alertmanager_storage:
                s3:
                  bucket_name: mimir-alertmanager
              ruler_storage:
                s3:
                  bucket_name: mimir-ruler

  destination:
    namespace: mimir
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
