apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: unifi-backend
  namespace: unifi
  labels:
    app.kubernetes.io/name: unifi
spec:
  type: Endpoints
  endpoints:
    - fqdn:
        hostname: unifi-gui.unifi.svc.cluster.local
        port: 8443
  tls:
    insecureSkipVerify: true
