apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-gateway-external
  namespace: envoy-gateway
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: envoy-gateway-external
        type: LoadBalancer
        loadBalancerClass: tailscale
        externalTrafficPolicy: Local
        annotations:
          external-dns.alpha.kubernetes.io/target: "k8s-ext-gateway.chik4ge.me"
