apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-gateway-external
  namespace: envoy-gateway
  annotations:
    external-dns.alpha.kubernetes.io/target: "k8s-ext-gateway.chik4ge.me"
spec:
  gatewayClassName: envoy-gateway
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: envoy-gateway-external
  listeners:
    - name: https
      allowedRoutes:
        namespaces:
          from: All
      hostname: "*.chik4ge.me"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: wildcard-chik4ge-me-tls
