apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-api-token-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    template:
      data:
        tunnel_name: homelab-k8s
  data:
    - secretKey: api_token
      remoteRef:
        key: "Cloudflare Account API Token (Tunnel for chik4ge.me)"
        property: token
    - secretKey: account_id
      remoteRef:
        key: "Cloudflare Account API Token (Tunnel for chik4ge.me)"
        property: account_id
