apiVersion: v1
kind: Service
metadata:
  name: tradukisto-server
  namespace: tradukisto
  labels:
    app.kubernetes.io/name: tradukisto-server
    app.kubernetes.io/part-of: tradukisto
spec:
  selector:
    app.kubernetes.io/name: tradukisto-server
  ports:
    - port: 8081
      targetPort: 8081
