apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-password
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  data:
    - secretKey: KAFKA_PASSWORD
      remoteRef:
        key: "Kafka mimir User"
        property: password
