apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 1.1.1
      helm:
        parameters:
          - name: resources.requests.cpu
            value: "10m"
          - name: resources.requests.memory
            value: "128Mi"
          - name: resources.limits.memory
            value: "256Mi"
          - name: certController.resources.requests.cpu
            value: "10m"
          - name: certController.resources.requests.memory
            value: "64Mi"
          - name: certController.resources.limits.memory
            value: "128Mi"
          - name: webhook.resources.requests.cpu
            value: "5m"
          - name: webhook.resources.requests.memory
            value: "32Mi"
          - name: webhook.resources.limits.memory
            value: "64Mi"
    - repoURL: https://github.com/chik4ge-homelab/homelab-applications
      targetRevision: main
      path: manifests/platform/base/secrets/external-secrets
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
