apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: external-pve-backend-tls
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: external-pve-backend
  validation:
    hostname: pve.chik4ge.me
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: pve-root-ca
