apiVersion: v1
kind: ConfigMap
metadata:
  name: pve-root-ca
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFzTCCA7WgAwIBAgIUOnVO/90teNMl0RFUYY6F6JUWpfowDQYJKoZIhvcNAQEL
    BQAwdjEkMCIGA1UEAwwbUHJveG1veCBWaXJ0dWFsIEVudmlyb25tZW50MS0wKwYD
    VQQLDCRkM2YxNmNiYS1lMTRkLTQ2ODItOTUyYS0wYzA4YTU5NzYzMzQxHzAdBgNV
    BAoMFlBWRSBDbHVzdGVyIE1hbmFnZXIgQ0EwHhcNMjQxMjE2MDkwOTIxWhcNMzQx
    MjE0MDkwOTIxWjB2MSQwIgYDVQQDDBtQcm94bW94IFZpcnR1YWwgRW52aXJvbm1l
    bnQxLTArBgNVBAsMJGQzZjE2Y2JhLWUxNGQtNDY4Mi05NTJhLTBjMDhhNTk3NjMz
    NDEfMB0GA1UECgwWUFZFIENsdXN0ZXIgTWFuYWdlciBDQTCCAiIwDQYJKoZIhvcN
    AQEBBQADggIPADCCAgoCggIBAJGQBU17YFMwnBhUtOSzB02LsswWmFPoBZJ44aPE
    tcakg8D9jpstUXuBfQ/pj0ZDRCHQe/CKNKZ1PSOr5kkB1/wg3RTWRjMV4rmn+qVk
    tQedrJL8g8tNdU7vmCB/VBFcW4P4k0YmZ5/i4jyjfamDKDnY5jxXTCXlo1sFQYSv
    AYl5eiY7KE/KLGRfN3GjWTo6B5hlwt769XFXhDSKnG59IlCs4RDtyLl7xACEj3D4
    fUw4stZyJ0AO9tqtAYEhaJSaOMDtczjAxQy6aOL1pJOBl2njJPOFCBdPLUJF78HH
    inG6qFPea1IQzUCyeWJtFRjWX4D2TD+HLGULaGZ4pjSJRxzn36SA5OwFmh5fvmJg
    kNJwWchqWN6IyoB5Vs/DQJISMaMQGSvQoA9lpv8IZNBd4/Pf7f0ebGPc5KopIkDQ
    tWNu0d57cWigrnZHZfGeUYW9SbnBCXLLJYQPh+zUkT7MZsxC/xCoO+vCz7Yawltl
    9x6JY9Wx/05hQDi3O1w9fvpS1qfGq0tBx2TNdFooVjSxoZsUp49xIhXU08cpSfIt
    7IMZyDD4L4BkZfip/UpEDu+uIsw28XP7VEWTbhs+yBvA7k0ySvLRC9u3aYbn+Enn
    nIY6ETxu0ECOju2ZBHYWBIfMGPGdKH6afVElRUOOK9rfZuSaXHIvyilba+Kg217p
    q/2xAgMBAAGjUzBRMB0GA1UdDgQWBBQ+tLCNCjpkT0BAau+iKGcdgeXr2TAfBgNV
    HSMEGDAWgBQ+tLCNCjpkT0BAau+iKGcdgeXr2TAPBgNVHRMBAf8EBTADAQH/MA0G
    CSqGSIb3DQEBCwUAA4ICAQBUFmXvyQoo/ThtHcj/sw/dy/w1eKCbAhRLeKz7/2x6
    w05LehvLDNC9jmlnuhLZ2V+Kscjp35gPRl6BTQRuIDZFZh5/7Hc3vRfmxYmbKsfB
    Y4klQkURdy5rucuIS89RY7F4YEn1gubWSZfiM8dvDvvfRVhqFCL3tId4QRuYrcyN
    n5c9l18kqW5q+zO+j1C6XeZ4yYWd/WexVLuvPgcV648ZHvG0aZE+Kte/WUgANaMm
    dsd/SRLuC9I3ycw/vhVyn+i8yJi0keUE1qNt8f05OWUGxyGrITx434raJ9xltkw5
    g/ok8x+9IsPTSXXicyl44ULdwigNsrTZmWykaiEHwA+PnaByOS5WObu/eBQZMDWC
    789Yer3vjPGUkSJwG4Yc2y4qoMQbUfSkoVFNEGRx7sf3vnlqWJ6suB+lJ27hi+v2
    hMSZww/MOkjY5DK4ja7/Hn9e6leJ2C8IQqHzkH02dmZx/YK5D1PkhMGTtD7LJyJl
    Ff3wbv6/v+RFR9I+MNCbo4JoTXFkG6VzzcgbKQU7ve9wa2N5uTQ7P9G57r0JO8hp
    I7RkDa4OBD19zWStM2jkUsYQ+W24YBdkqyNQah8uTTsMi103NzyL6o1mdKyYZE2d
    897UHuxDiuwyQoUdC23VYHUTlTfNY5IbjIYoz5OEbYjsE0ZBRpReltjUQ9Sy7o/6
    +A==
    -----END CERTIFICATE-----
