apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-pve-route
  namespace: pve-lb
spec:
  parentRefs:
    - name: envoy-gateway-internal
      namespace: envoy-gateway
      sectionName: https
  hostnames:
    - "pve.chik4ge.me"
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: external-pve-backend
          port: 8006
