apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./service.yaml
  - ./endpointslice.yaml
  - ./httproute.yaml
  - ./trafficpolicy.yaml
  - ./backendtlspolicy.yaml
  - ./ca-configmap.yaml
