apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: haproxy-config
    files:
      - haproxy.cfg
generatorOptions:
  disableNameSuffixHash: false
