apiVersion: v1
kind: Service
metadata:
  name: tradukisto-client
  namespace: tradukisto
  labels:
    app.kubernetes.io/name: tradukisto-client
    app.kubernetes.io/part-of: tradukisto
spec:
  selector:
    app.kubernetes.io/name: tradukisto-client
  ports:
    - port: 80
      targetPort: 80
