apiVersion: v1
kind: Endpoints
metadata:
  name: external-rgw-backend
subsets:
  - addresses:
      - ip: 192.168.0.150
      - ip: 192.168.0.151
      - ip: 192.168.0.152
      - ip: 192.168.0.153
    ports:
      - name: http
        port: 7480
        protocol: TCP
