apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-rgw-route
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway
      sectionName: https
  hostnames:
    - "rgw.chik4ge.me"
  rules:
    - backendRefs:
        - name: external-rgw-backend
          port: 7480
