apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: external-rgw-route-policy
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: external-rgw-route
  healthCheck:
    active:
      type: HTTP
      interval: 5s
      timeout: 2s
      unhealthyThreshold: 3
      healthyThreshold: 1
      http:
        path: /swift/healthcheck
        expectedStatuses:
          - 200
  loadBalancer:
    type: RoundRobin
