apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-pve-exporter-secret
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        tokenName: "{{ .tokenId | trimPrefix \"prometheus@pve!\" }}"
        tokenValue: "{{ .tokenValue }}"
  data:
    - secretKey: tokenId
      remoteRef:
        key: "Proxmox exporter Credentials"
        property: token_id
    - secretKey: tokenValue
      remoteRef:
        key: "Proxmox exporter Credentials"
        property: token
