apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-pve-exporter-secret
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  data:
    - secretKey: tokenName
      remoteRef:
        key: "Proxmox exporter Credentials"
        property: token_id
    - secretKey: tokenValue
      remoteRef:
        key: "Proxmox exporter Credentials"
        property: token
