apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-chunks
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: "Loki Ceph Credentials"
        property: accessKey
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: "Loki Ceph Credentials"
        property: secretKey
  dataFrom:
    - extract:
        key: "Loki Ceph Connection"
