apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alloy
  namespace: alloy
  labels:
    app.kubernetes.io/name: alloy
spec:
  parentRefs:
    - name: envoy-gateway-external
      namespace: envoy-gateway
      sectionName: https
  hostnames:
    - alloy.chik4ge.me
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: alloy
          port: 12345
