apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate-ca.yaml
  - cloudflare-api-token-secret.yaml
  - issuer-ca.yaml
  - issuer-chik4ge-me.yaml
  - issuer-selfsigned.yaml
  - rules/mixin-generated/cert-manager-mixin-rules.yaml
  - rules/mixin-generated/cert-manager-mixin-alerts.yaml
